### ISSUE TITLE
recipesByUser

### ISSUE THREAD

**Issue by lkriffell** [feed-the-people/Back-End#44]
FE should be able to query all of a user's created recipes, along with that recipes ingredients

**Comment by hashmaster3k** [comment]
This can be merged with getUser. I believe when you call to get a user you can use the relationship of getting all of that user's recipes too and ingredients.

**Comment by hashmaster3k** [comment]
Closing. Example of request/response:
<img width="1156" alt="Screen Shot 2021-01-06 at 4 11 18 PM" src="https://user-images.githubusercontent.com/40395852/103831677-d1507100-5039-11eb-8f65-bf8aa14a24f0.png">
